config/routes.rb
Bling::Application.routes.draw do

  root :to => 'blings#index'

  match '/test' => 'welcome#test'
  match '/test/tone/:frequency' => 'welcome#testTone'
  match '/test/slide/:startFreq/:endFreq' => 'welcome#slideTone'
  match '/test/3rd/:startFreq/:endFreq' => 'welcome#slide3rd'

  # get '/blings_api/:ticker' => 'blings_api#bling_path'
  # get '/blings_api/:email_hash/:ticker' => 'blings_api#bling_path'

  match '/bling' => 'blings#bling'
  match '/bling/:ticker' => 'blings#bling'

  get 'sessions/new' => 'sessions#new'
  post 'sessions' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users, only: [:new, :create, :index, :destroy, :show]
  post 'users/:id' => 'users#show'
  resources :portfolios

end

app/models/user.rb
class User < ActiveRecord::Base
  
  attr_accessible :email, :name, :username, :password, :portfolios
  
  has_many :portfolios
  has_many :stocks, :through => :portfolios
  
  has_secure_password
  
  validates :email, presence: true, uniqueness:true
  validates :password, presence: true, length: {in: 6..20}

  def clear_portfolios
    self.portfolios.each {|portfolio| portfolio.destroy}
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  include ApplicationHelper

  before_filter :ensure_admin, only: [:index, :destroy]

  def index
    @user = []
    if current_user && current_user.admin?
      @users = User.all
    end
  end

  def new
    if current_user
      redirect_to user_path(current_user)
    end
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      @user.email = @user.email.downcase
      redirect_to sessions_new_path
    else
      render :new
    end
  end

  def destroy
    user = User.find(params[:id])
    user.clear_portfolios
    user.destroy
    redirect_to :back
  end


  def show
    puts params
    @user = User.find(params[:id])
    @newPortfolio = Portfolio.new
    
    if @user
      @portfolios = @user.portfolios

      if params[:ticker] && params[:seconds]

        params[:seconds] = params[:seconds].to_f
        if params[:seconds] > 5
          params[:seconds] = 5
        elsif params[:seconds] <= 0
          params[:seconds] = 0.05
        end

        @path = nil
        emailHash = email_hash(@user.email)
        ticker = params[:ticker]
        if ticker
          testPath = (Rails.root.to_s + "/public/audio/user_audio/#{emailHash}-#{params[:seconds].to_s}-#{ticker}.wav")
          Dir[Rails.root.to_s + "/public/audio/user_audio/*"].each do |filename|
            if filename == testPath
              @path = "/audio/user_audio/#{emailHash}-#{params[:seconds].to_s}-#{ticker}.wav"
            end
          end
        end

        if @path.nil?
          @companyName, close, open = nil
          open, close, @companyName = getStockPrices(ticker)

          if close && open && @companyName && close > 0 && open > 0
            maxNum = [open, close].max
            open = ((open/maxNum)**4)*440 + 100
            close = ((close/maxNum)**4)*440 + 100
            s = Synth.new({path: $absolute_path_user_audio, filename: "#{emailHash}-#{params[:seconds].to_s}-#{ticker}",  seconds:params[:seconds]})
            s.makeSlide3rd(open.to_f, close.to_f)
            s.normalize
            s.applyFades(100)
            absolutePath = s.writeWave

            manageAudioFiles(100, 'user_audio')

            @path = absolutePath.gsub($absolute_prepath, "/")
          end
        end
      end
    end

  end


  private

  def ensure_admin
    unless current_user && current_user.admin?
      render text: 'not allowed'
    end
  end



end

app/views/users/index.html.haml
.container
  %h1
    Users
.container
  %table{class:'table table-hover table-striped'}
    %thead
      %tr
        %th
          ID
        %th
          Username
        %th
          Email
        %th
          Admin
        %th
          Portfolios
        %th
          Delete
    %tbody
      - @users.each do |user|
        %tr
          %td
            = user.id
          %td
            = user.username
          %td
            = user.email
          %td
            = user.admin?
          %td
            -if user.portfolios
              = user.portfolios.count
            -else
              0
          %td
            = link_to('delete', user_path(user), {method: :delete, confirm: 'Are you sure?', class:"btn btn-danger"}) unless user==current_user 

app/views/users/new.html.haml
= render partial: 'users/partials/form'

app/views/users/show.html.haml
/ Main page text and search
#upper_mpt_user.container
  %p
    Create a portfolio of Blings!
#lower_mpt_user.container
  %p
    Enter a stock ticker to add one.

#main_search.container
  = form_for @newPortfolio, :html => { class:"form-search"} do |f|
    .input-append
      = f.text_field :name, {class: 'span4 search-query', :autofocus=>true}
      = f.submit 'Submit', {class:'btn', name:'commit'}
      
%br
%br
.container
  %h1 
    = @user.username

.container
  - if @user.portfolios.any?
    %table{class:'table table-hover table-striped'}
      %thead
        %tr
          %th
            Ticker
          %th
            Company
          %th
            Blings
          %th
            Delete
      %tbody
        - @user.portfolios.each do |portfolio|
          - if portfolio.stocks
            - portfolio.stocks.each do |stock|
              %tr
                %td
                  = stock.ticker
                %td
                  = stock.name
                %td
                  = link_to '0.25', user_path(:ticker =>  stock.ticker, :seconds => 0.25), {class:"btn", method: :post}
                  = link_to '0.5', user_path(:ticker =>  stock.ticker, :seconds => 0.5), {class:"btn", method: :post}
                  = link_to '1.0', user_path(:ticker =>  stock.ticker, :seconds => 1.0), {class:"btn", method: :post}
                  = link_to '2.0', user_path(:ticker =>  stock.ticker, :seconds => 2.0), {class:"btn", method: :post}
                %td
                  = link_to 'Delete', portfolio_path(portfolio), {confirm: "Are you sure you want to delete this user?", class:"btn btn-danger", method: :delete}

- if @path
  %span
    %embed{:height => "0", :src => @path, :width => "0"}