config/routes.rb
Bling::Application.routes.draw do

  root :to => 'blings#index'

  match '/test' => 'welcome#test'
  match '/test/tone/:frequency' => 'welcome#testTone'
  match '/test/slide/:startFreq/:endFreq' => 'welcome#slideTone'
  match '/test/3rd/:startFreq/:endFreq' => 'welcome#slide3rd'

  # get '/blings_api/:ticker' => 'blings_api#bling_path'
  # get '/blings_api/:email_hash/:ticker' => 'blings_api#bling_path'

  match '/bling' => 'blings#bling'
  match '/bling/:ticker' => 'blings#bling'

  get 'sessions/new' => 'sessions#new'
  post 'sessions' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users, only: [:new, :create, :index, :destroy, :show]
  post 'users/:id' => 'users#show'
  resources :portfolios

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bling</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar" >
   <nav class="navbar-inner">
     <nav class="nav-collapse collapse">
       <ul class="nav">
        <% if current_user %>
           <%= link_to('Blings', user_path(current_user), {class:"brand", id:"nav"}) %>
         <% else %>
           <a class="brand" href="/" id="nav">Blings</a>
         <% end %>
       </ul>
       <div class="nav navbar-text pull-right">

            <% if current_user %>
              <%= link_to('Log-Out', '/logout', {:method=>:delete, :class=>"", :id=>"logout"} ) %>
            <% else %>
              <%= link_to('New-User', new_user_path, {:class=>"", :id=>"login"}) %>
              <%= link_to('Log-In', sessions_new_path, {:class=>"", :id=>"login"}) %>
            <% end %>

            <% if current_user && current_user.admin? %>
              <%= link_to('All-Users', users_path, {:class=>"", :id=>"login"}) %>
            <% end %>

       </div>
     </nav>
   </nav>
 </nav>





<%= yield %>

</body>
</html>